### ISSUE TITLE
Chrome crash workaround

### ISSUE THREAD

**Issue by lePereT** [seanmpuckett/Myriad-Pro-System-Font-for-Yosemite#2]
If you use Myriad Web Pro as the regular font, then Chrome works (with only minor alignment issues in the tabs). Alignment throughout the OS is perfect.

Web Pro is a hint more expanded than Pro but still very pleasing. So much better than Helvetica Neue.

**Comment by lmartins** [comment]
Chrome is crashing to me too. What do you mean by "use Myriad Web Pro as the regular font" ?

**Comment by lePereT** [comment]
https://github.com/dtinth/YosemiteSystemFontPatcher

Scroll down to the manual instructions and use the regular weight of Myriad Web Pro (a font that’s different from standard Myriad Pro) as the regular weight.

On 5 January 2015 at 12:32:01, Luis Martins (notifications@github.com) wrote:

Chrome is crashing to me too. What do you mean by "use Myriad Web Pro as the regular font" ?

**Comment by chethankumar** [comment]
@lePereT Can you please share your modified Myriad Web Pro fonts.
